#if defined _JAILBREAK_included
 #endinput
#endif
#define _JAILBREAK_included

#define PREFIX " \x05[WePlay]\x01"
#define MENU_PREFIX "[WePlay]"
#define PREFIX_ACTIVITY " \x04[WePlay]\x01 "

#define GANG_NULL ""
#define GANGID_NULL 0

#define RANK_NULL -1
#define RANK_MEMBER 0
#define RANK_ENFORCER 1
#define RANK_ADVISOR 2
#define RANK_MANAGER 3
#define RANK_COLEADER 4
#define RANK_LEADER 420